id = "zed-slack-mcp"
name = "Zed Slack MCP"
description = "Zed Extension for Slack's Model Context Server"
version = "0.0.1"
schema_version = 1
authors = ["Semih Berkay Öztürk <semihozt@gmail.com"]
repository = "https://github.com/semioz/zed-slack-mcp"

[context_servers.zed-slack-mcp]
name = "Slack Model Context Protocol Server"