id = "zed-slack-mcp"
name = "Zed Slack MCP"
description = "Zed Extension for Slack's Model Context Server"
version = "0.1.0"
schema_version = 1
authors = ["Semih Berkay Öztürk <90466553+semioz@users.noreply.github.com>"]
repository = "https://github.com/semioz/zed-slack-mcp"

[context_servers.zed-slack-mcp]
name = "Slack Model Context Protocol Server"